name: CI

on:
  # User브랜치의 내용만 CI
  push:
    branches: [ "User" ]
  pull_request:
    branches: [ "User" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# This workflow contains a single job called "build"
jobs:
  build:
    # runner의 종류
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: JDK 17 설치
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: MySQL 설정
        uses: mirromutth/mysql-action@v1.1
        with:
          # host port: 3306 # default value is 3306. The port of host
          # container port: 3306 # default value is 3306. The port of container
          character set server: 'utf8' #default value is 'utf8mb4'
          collation server: 'utf8_general_ci' # default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
          mysql version: '8.0.33' # Optional, default value is "latest". The version of the MySQL
          # mysql database: 'some_test' # Optional, default value is "test". The specified database which will be create
          mysql root password: ${{ secrets.RDS_USER_PASSWORD }} # 이 항목을 작성하거나 아래 두 항목을 작성해야한다.
          # mysql user: admin
          # mysql password: ${{ secrets.ROOT_PASSWORD }}

      - name: application.yml 생성
        shell: bash
        run: |
          mkdir User/src/main/resources # 레포지토리에 여러 프로젝트가 존재하는 구조라 해당 프로젝트 폴더로 이동하여 수행한다.
          cd User/src/main/resources
          touch ./application.yml

          echo "${{ secrets.USER_APPLICATIONYML }}" >> ./application.yml
          
      - name: Grant execute permission for gradlew
        run: chmod +x User/gradlew
      
      - name: Build with Gradle
        run: |
          cd User # 레포지토리에 여러 프로젝트가 존재하는 구조라 해당 프로젝트 폴더로 이동하여 수행한다.
          ./gradlew clean --stacktrace --info build

      - name: archive drcloud 
        run: tar cvfz ./user.tar.gz User/*
         
      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.USER_ACCESS }}
          aws-secret-access-key: ${{ secrets.USER_SECRET_ACCESS }}
          aws-region: ap-northeast-2
          
      - name: upload to S3
        run: aws s3 cp --region ap-northeast-2 ./user.tar.gz s3://scalablemsa-deployarchive/user-service/
        
      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name codedeploy-user
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name deploy-group-user
          --s3-location bucket=scalablemsa-deployarchive,bundleType=tgz,key=user-service/user.tar.gz
